# Generated by Django 2.2.5 on 2019-09-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('1', 'fundacja'), ('2', 'organizacja pozarządowa'), ('3', 'zbiórka lokalna')], default=3, max_length=50),
        ),
    ]
