# Generated by Django 2.2.5 on 2019-09-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0002_auto_20190918_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('1', 'fundacja'), ('2', 'organizacja pozarządowa'), ('3', 'zbiórka lokalna')], default=1, max_length=50),
        ),
    ]
